#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.2.0
    environment:
      - SFDX_URL_LINUX=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - SFDX_AUTOUPDATE_DISABLE=true
      - SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
      - SFDX_DOMAIN_RETRY=300

    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      # Setup an NODE_ENV to production mode before compiling.
      - run:
          name: 'Run compile in production mode'
          command: |
            export NODE_ENV=production && yarn compile
      - run: yarn vscode:package
      - run:
          command: |
            mkdir extensions
            find . -name "*.vsix" -type f -exec cp {} ./extensions \;
      - store_artifacts:
          path: ./extensions
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - develop
                - master
    jobs:
      - build
